version: '3'

secrets:
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt
  jwt_private_key:
    file: ./secrets/jwt_private_key.pem
  jwt_public_key:
    file: ./secrets/jwt_public_key.pem
  pepper_key:
    file: ./secrets/pepper_key.txt

services:
  database:
    image: 'postgres'
    ports:
      - "5432:5432"
    secrets:
      - db_user
      - db_password
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    restart: unless-stopped
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    secrets:
      - db_user
      - db_password
      - jwt_private_key
      - jwt_public_key
      - pepper_key
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER_FILE: /run/secrets/db_user
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_NAME: messenger
      MAX_OPEN_CONNS: 5
      MAX_IDLE_CONNS: 2
      JWT_PRIVATE_KEY_FILE: /run/secrets/jwt_private_key
      JWT_PUBLIC_KEY_FILE: /run/secrets/jwt_public_key
      BCRYPT_COST: 15
      PEPPER_KEY_FILE: /run/secrets/pepper_key
    restart: unless-stopped