name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: finnp/create-file-action@master
      env:
        FILE_NAME: secrets/db_user.txt
        FILE_DATA: ${{ secrets.DB_USER }}
        
    - uses: finnp/create-file-action@master
      env:
        FILE_NAME: secrets/db_password.txt
        FILE_DATA: ${{ secrets.DB_PASSWORD }}
      
    - uses: finnp/create-file-action@master
      env:
        FILE_NAME: secrets/jwt_private_key.pem
        FILE_DATA: ${{ secrets.JWT_PRIVATE_KEY }}
        
    - uses: finnp/create-file-action@master
      env:
        FILE_NAME: secrets/jwt_public_key
        FILE_DATA: ${{ secrets.JWT_PUBLIC_KEY }}
        
    - uses: finnp/create-file-action@master
      env:
        FILE_NAME: secrets/pepper_key.txt
        FILE_DATA: ${{ secrets.PEPPER_KEY }}
        
    - name: Test printing your secret (Remove this step in production)
      run: cat secrets/jwt_public_key
