name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: finnp/create-file-action@master
      env:
        FILE_NAME: db_user.txt
        FILE_DATA: ${{ secrets.DB_USER }}
